import eslint from '@eslint/js';
import eslintConfigPrettier from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.strict,
  ...tseslint.configs.stylistic,
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.expo/**',
      '**/android/**',
      '**/ios/**',
      '**/babel.config.js',
      '**/metro.config.js',
      // Generated by `pnpm db:types` (supabase CLI) — not hand-authored, don't lint for style.
      '**/database.types.ts',
      // Gitignored local scratch harnesses (see .gitignore); not part of the repo.
      'scripts/tmp-*.ts',
    ],
  },
  {
    files: ['**/*.{ts,tsx,mts,cts}'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Interface implementations sometimes can't use every parameter (e.g. a
      // FantasyProvider method that's a no-op for one platform); leading underscore
      // is the standard escape hatch.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // The root entry re-exports server-only code (the @sentry/node reporter), which Metro can't
    // bundle for iOS. `paths` matches the exact specifier, so `@pivot/shared/broadcast` is allowed.
    files: ['app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@pivot/shared',
              message:
                "Import from '@pivot/shared/broadcast'. The root entry pulls in server-only code (@sentry/node).",
            },
          ],
        },
      ],
    },
  },
  eslintConfigPrettier,
);
